### ISSUE TITLE
JS error in chrome

### ISSUE THREAD

**Issue by VegaDiscoveries** [xxjapp/xdialog#1]
**Describe the bug**
After adding xdialog to my project the code produced an error in the debugger.

**To Reproduce**
1. Add js file to a web page
2. Open chrome devtools
3.  Open web page in chrome
4. View error on devtools

**Expected behavior**
Open web page with no errors

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 123.0.6312.106

Solution
Line 438:             document.body.insertAdjacentElement('beforeend', overlayElement);
Replace with:
        var ele = document.body;
        if (ele) {
            ele.insertAdjacentElement('beforeend', overlayElement);
        }

**Comment by xxjapp** [comment]
@VegaDiscoveries 

Thank you for your report. I will fix this problem. 
Before that you may add the script tag just before </body> like this. 

```html
<body>
...


    <script src="xdialog.js"></script>
</body>
```

**Comment by xxjapp** [comment]
@VegaDiscoveries 

fixed: https://github.com/xxjapp/xdialog/commit/e2e31ea677c737ad300196760ed98a0898ae22e1
