### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'querySelector') in xdialog.startSpin()

### ISSUE THREAD

**Issue by Kashif2016** [xxjapp/xdialog#3]
Describe the bug
I am using `xdialog.startSpin();` in `$(document).ready(function() {.....});`. It was working fine from months, but now it is throwing `Uncaught TypeError: Cannot read properties of null (reading 'querySelector')` error.
Tested on Edge and Chrome browsers.

To Reproduce
Add `xdialog.startSpin();` in `$(document).ready(function() {.....});` and launch then website.

Expected behavior
I am expecting to see the spinner/loader.

Screenshots
![error on console](https://github.com/xxjapp/xdialog/assets/23480875/bd081521-0c9a-4e88-bec5-f087c28cd103)
![error details](https://github.com/xxjapp/xdialog/assets/23480875/d53fe359-b675-41e0-b42f-2130deff4756)

Desktop (please complete the following information):

OS: Windows
Browser: Chrome (Version 124.0.6367.91 (Official Build) (64-bit)), Edge (Version 124.0.2478.51 (Official build) (64-bit))

**Comment by xxjapp** [comment]
Fixed.

https://github.com/xxjapp/xdialog/commit/b60e677db897888851c88c5ee8071e87a4420083

**Comment by xxjapp** [comment]
New version released:

https://github.com/xxjapp/xdialog/releases/tag/v3.4.2
