### ISSUE TITLE
Responsive dialog

### ISSUE THREAD

**Issue by radiolondra** [xxjapp/xdialog#6]
Is it possible to make a shown dialog responsive when the browser is resized?
Actually the behaviour is like as shown in this video: https://app.screencast.com/wjwqpGEmcmBUg
I wish to have the dialog responsive (moved to the center of the browser when resized)
Thanks

**Comment by xxjapp** [comment]
@radiolondra 

You can try specifying the option `fixChromeBlur: false`.

For example, modify

```javascript
xdialog.open({
    title: 'Hello, xdialog',
    body: 'This is a message.'
});
```

to

```javascript
xdialog.open({
    title: 'Hello, xdialog',
    body: 'This is a message.',
    fixChromeBlur: false
});
```
